"""Public corpus rebuild and rematerialization behavior.

The archive is generated by RiichiEnv so this suite owns its input contract.
It intentionally does not load any retained integration fixture.
"""

import hashlib
import json
import pathlib
import sqlite3
import subprocess
import sys
import zipfile

import riichienv
import tensorflow as tf

from log_dataset import afk, player_ranks


def write_enriched_archive(root):
    """Write one valid, rank-enriched 2024 MJAI game."""
    environment = riichienv.RiichiEnv(
        seed=14, rule=riichienv.GameRule.default_tenhou()
    )
    observations = environment.reset()
    while not environment.done():
        observations = environment.step(
            {
                seat: observation.legal_actions()[0]
                for seat, observation in observations.items()
            }
        )
    events = environment.mjai_log
    events[0]["player_ranks"] = {
        "dan": [9, 9, 9, 9],
        "rating": [2500.0] * 4,
        "retained_seats": [0, 1, 2, 3],
    }
    archive = root / "2024.zip"
    member = "2024010100gm-00a9-0000-rewrite.mjson"
    with zipfile.ZipFile(archive, "w", zipfile.ZIP_DEFLATED) as output:
        output.writestr(
            member,
            "".join(json.dumps(event) + "\n" for event in events),
        )
    checksum = hashlib.file_digest(archive.open("rb"), "sha256").hexdigest()
    (root / "player_ranks.json").write_text(
        json.dumps(
            {
                "sampling": player_ranks.SAMPLING,
                "years": {"2024": {"merged_sha256": checksum}},
            }
        )
    )
    return archive


def command(*arguments):
    return [sys.executable, *arguments]


def all_tsumogiri_round(seed):
    environment = riichienv.RiichiEnv(
        seed=seed, rule=riichienv.GameRule.default_tenhou()
    )
    observations = environment.reset()
    while not environment.done():
        choices = {}
        for seat, observation in observations.items():
            legal = observation.legal_actions()
            choices[seat] = next(
                (
                    action
                    for action in legal
                    if action.action_type == riichienv.ActionType.DISCARD
                    and action.tile == observation.drawn_tile
                ),
                next(
                    (
                        action
                        for action in legal
                        if action.action_type == riichienv.ActionType.PASS
                    ),
                    legal[0],
                ),
            )
        observations = environment.step(choices)
    return environment.mjai_log[1:-1]


def test_rebuild_indexes_an_enriched_archive_then_rematerializes_from_sqlite(
    tmp_path,
):
    archives = tmp_path / "archives"
    archives.mkdir()
    archive = write_enriched_archive(archives)
    corpus = tmp_path / "corpus"

    subprocess.run(
        command(
            "-m",
            "log_dataset.rebuild",
            "--archives",
            str(archives),
            "--output",
            str(corpus),
            "--experiment",
        ),
        check=True,
    )

    database = corpus / "decisions.sqlite"
    with sqlite3.connect(database) as connection:
        positions = connection.execute(
            "SELECT COUNT(*) FROM positions"
        ).fetchone()[0]
        discard_summary = connection.execute(
            "SELECT COUNT(*), MIN(shanten), MAX(ukeire_count) "
            "FROM discard_actions"
        ).fetchone()
    assert positions > 0
    assert discard_summary[0] >= positions
    assert discard_summary[1] >= -1
    assert discard_summary[2] > 0

    archive.unlink()
    rematerialized = tmp_path / "rematerialized"
    subprocess.run(
        command(
            "-m",
            "log_dataset.materialize",
            "--database",
            str(database),
            "--output",
            str(rematerialized),
        ),
        check=True,
    )

    rows = sum(
        1
        for path in rematerialized.glob("*.tfrecord.gz")
        for _ in tf.data.TFRecordDataset(str(path), compression_type="GZIP")
    )
    summary = json.loads((rematerialized / "dataset_summary.json").read_text())
    assert rows == positions == summary["examples"]


def test_rebuild_rejects_an_archive_without_rank_enrichment(tmp_path):
    archives = tmp_path / "archives"
    archives.mkdir()
    archive = write_enriched_archive(archives)
    with zipfile.ZipFile(archive) as source:
        member = source.namelist()[0]
        events = [json.loads(line) for line in source.read(member).splitlines()]
    del events[0]["player_ranks"]
    with zipfile.ZipFile(archive, "w", zipfile.ZIP_DEFLATED) as output:
        output.writestr(
            member, "".join(json.dumps(event) + "\n" for event in events)
        )
    checksum = hashlib.file_digest(archive.open("rb"), "sha256").hexdigest()
    (archives / "player_ranks.json").write_text(
        json.dumps(
            {
                "sampling": player_ranks.SAMPLING,
                "years": {"2024": {"merged_sha256": checksum}},
            }
        )
    )

    result = subprocess.run(
        command(
            "-m",
            "log_dataset.rebuild",
            "--archives",
            str(archives),
            "--output",
            str(tmp_path / "corpus"),
            "--experiment",
        ),
        text=True,
        capture_output=True,
    )

    assert result.returncode
    assert "player_ranks" in result.stderr


def test_afk_filter_removes_every_seat_from_two_tsumogiri_hands():
    first = all_tsumogiri_round(1)
    second = all_tsumogiri_round(2)

    retained = afk.retained_hands(
        [{"type": "start_game"}, *first, *second, {"type": "end_game"}]
    )

    assert retained == []
