"""Public corpus rebuild and rematerialization behavior.

The archive is generated by RiichiEnv so this suite owns its input contract.
It intentionally does not load any retained integration fixture.
"""

import hashlib
import json
import sqlite3
import subprocess
import sys
import zipfile

import numpy
import pytest
import riichienv
import tensorflow as tf

from log_dataset import afk, cache, player_ranks, rebuild, shanten
from model import critic_data, features, payment_scoring, records, replay


def test_critic_filter_preserves_partition_order_and_partial_metadata_batch(
    tmp_path,
):
    rows = [
        tf.train.Example(
            features=tf.train.Features(
                feature={
                    name: tf.train.Feature(
                        int64_list=tf.train.Int64List(value=[value])
                    )
                    for name, value in {
                        "critic/partition": index % 10,
                        "meta/focused": int(index % 3 != 0),
                        "test/index": index,
                    }.items()
                }
            )
        ).SerializeToString()
        for index in range(2051)
    ]
    with tf.io.TFRecordWriter(
        str(tmp_path / "train-00000.tfrecord.gz"), options="GZIP"
    ) as writer:
        for row in rows:
            writer.write(row)
    (tmp_path / "dataset_summary.json").write_text(
        json.dumps(
            {
                **records.DATA_CONTRACT,
                "critic_auxiliary": critic_data.AUXILIARY,
                "critic_scoring_states": [
                    list(s) for s in payment_scoring.SCORES
                ],
                "shard_manifest": [{"path": "train-00000.tfrecord.gz"}],
            }
        )
    )
    for partition in ("train", "validation"):
        for sampling in ("focused", "natural"):
            actual = [
                bytes(row.numpy())
                for batch in critic_data.dataset(
                    root=tmp_path,
                    sampling=sampling,
                    partition=partition,
                    batch_size=4,
                    repeat=False,
                )
                for row in batch
            ]
            expected = [
                row
                for index, row in enumerate(rows)
                if (index % 10 < 7 if partition == "train" else index % 10 == 7)
                and (index % 3 != 0 if sampling == "focused" else True)
            ]
            assert actual == expected[: len(expected) // 4 * 4]

    # A resumed stream starts immediately with a different reproducible shuffle.
    batches = []
    for seed in (941, 185941, 185941):
        batches.append(
            next(
                iter(
                    critic_data.dataset(
                        root=tmp_path,
                        sampling="focused",
                        partition="train",
                        batch_size=32,
                        repeat=True,
                        seed=seed,
                    )
                )
            )
            .numpy()
            .tolist()
        )
    assert batches[0] != batches[1]
    assert batches[1] == batches[2]
    for row in batches[1]:
        example = tf.train.Example.FromString(row).features.feature
        assert example["critic/partition"].int64_list.value[0] < 7
        assert example["meta/focused"].int64_list.value[0] == 1


def write_enriched_archive(root):
    """Write one valid, rank-enriched 2024 MJAI game."""
    environment = riichienv.RiichiEnv(
        seed=14, rule=riichienv.GameRule.default_tenhou()
    )
    observations = environment.reset()
    while not environment.done():
        observations = environment.step(
            {
                seat: observation.legal_actions()[0]
                for seat, observation in observations.items()
            }
        )
    events = environment.mjai_log
    events[0]["player_ranks"] = {
        "dan": [9, 9, 9, 9],
        "rating": [2500.0] * 4,
        "retained_seats": [0, 1, 2, 3],
    }
    archive = root / "2024.zip"
    member = "2024010100gm-00a9-0000-rewrite.mjson"
    with zipfile.ZipFile(archive, "w", zipfile.ZIP_DEFLATED) as output:
        output.writestr(
            member,
            "".join(json.dumps(event) + "\n" for event in events),
        )
    checksum = hashlib.file_digest(archive.open("rb"), "sha256").hexdigest()
    (root / "player_ranks.json").write_text(
        json.dumps(
            {
                "sampling": player_ranks.SAMPLING,
                "years": {"2024": {"merged_sha256": checksum}},
            }
        )
    )
    return archive


def command(*arguments):
    return [sys.executable, *arguments]


def all_tsumogiri_round(seed):
    environment = riichienv.RiichiEnv(
        seed=seed, rule=riichienv.GameRule.default_tenhou()
    )
    observations = environment.reset()
    while not environment.done():
        choices = {}
        for seat, observation in observations.items():
            legal = observation.legal_actions()
            choices[seat] = next(
                (
                    action
                    for action in legal
                    if action.action_type == riichienv.ActionType.DISCARD
                    and action.tile == observation.drawn_tile
                ),
                next(
                    (
                        action
                        for action in legal
                        if action.action_type == riichienv.ActionType.PASS
                    ),
                    legal[0],
                ),
            )
        observations = environment.step(choices)
    return environment.mjai_log[1:-1]


@pytest.mark.parametrize("workers", (1, 2))
def test_rebuild_indexes_an_enriched_archive_then_rematerializes_from_sqlite(
    tmp_path,
    workers,
):
    archives = tmp_path / "archives"
    archives.mkdir()
    archive = write_enriched_archive(archives)
    corpus = tmp_path / "corpus"

    subprocess.run(
        command(
            "build_dataset.py",
            "--archives",
            str(archives),
            "--output",
            str(corpus),
            "--workers",
            str(workers),
        ),
        check=True,
    )

    database = corpus / "decisions.sqlite"
    with sqlite3.connect(database) as connection:
        plan = connection.execute(
            "EXPLAIN QUERY PLAN " + cache.export_query(),
            connection.execute("SELECT MIN(id), MAX(id) FROM hands").fetchone(),
        ).fetchall()
        assert not any("TEMP B-TREE" in row[3] for row in plan)
        assert connection.execute("PRAGMA foreign_key_check").fetchall() == []
        positions = connection.execute(
            "SELECT COUNT(*) FROM selection WHERE retained = 1"
        ).fetchone()[0]
        assert positions > 0
        assert {
            row[0] for row in connection.execute("SELECT name FROM stages")
        } == set(cache.DEPENDENCIES)
        assert not connection.execute(
            "SELECT name FROM sqlite_schema WHERE name = 'records'"
        ).fetchall()
        game_id, game_name, hanchan = connection.execute(
            "SELECT id, game_id, hanchan FROM games"
        ).fetchone()
        for hand_id, events in connection.execute(
            "SELECT id, events FROM hands WHERE game_id = ?", (game_id,)
        ):
            packed = cache.feature_rows(
                connection, hand_id, tuple(cache.FEATURE_TABLES)
            )
            participation = dict(
                ((decision, actor), numpy.frombuffer(raw, numpy.float32))
                for decision, actor, raw in connection.execute(
                    "SELECT decision_index, actor, probabilities "
                    "FROM tile_participation WHERE hand_id = ?",
                    (hand_id,),
                )
            )
            state = replay.Replay(
                game_name, json.loads(events), json.loads(hanchan)
            )
            for _, actor, phase, _, _ in state.policy_decisions():
                direct = features.pack(
                    state, actor, phase, state.legal_observation(actor)
                )
                key = (state.decision_index, actor)
                for name in direct:
                    numpy.testing.assert_array_equal(
                        packed[key][name], direct[name], err_msg=name
                    )
                cuts = numpy.flatnonzero(direct["discard_action_legal"])
                if len(cuts):
                    numpy.testing.assert_array_equal(
                        participation[key],
                        shanten.tenpai_participation(
                            direct["candidate_hand_counts"][0],
                            direct["known_unavailable_counts"],
                            cuts,
                        ),
                    )
        exported = [
            tf.train.Example.FromString(bytes(row.numpy()))
            for row in tf.data.TFRecordDataset(
                str(corpus / "train-00000.tfrecord.gz"), compression_type="GZIP"
            )
        ]
        # Independent on-the-fly generation still agrees with every cache field.
        with zipfile.ZipFile(archive) as source:
            events = [
                json.loads(line)
                for line in source.read(source.namelist()[0]).splitlines()
            ]
        expected = []
        for hand in afk.retained_hands(events):
            state = replay.Replay(
                game_name, hand, replay.hanchan_targets(events)
            )
            expected.extend(
                tf.train.Example.FromString(
                    records.serialize_observation(
                        row, rebuild.retain_focused(row)
                    )
                )
                for row in state.observations()
            )
        assert exported == expected
        cached_batch = next(
            iter(
                tf.data.TFRecordDataset(
                    str(corpus / "train-00000.tfrecord.gz"),
                    compression_type="GZIP",
                ).batch(len(expected))
            )
        )
        direct_batch = tf.constant(
            [row.SerializeToString() for row in expected]
        )
        for cached_value, direct_value in zip(
            tf.nest.flatten(records.parse_batch(cached_batch)),
            tf.nest.flatten(records.parse_batch(direct_batch)),
            strict=True,
        ):
            numpy.testing.assert_array_equal(cached_value, direct_value)

    archive.unlink()
    rematerialized = tmp_path / "rematerialized"
    subprocess.run(
        command(
            "export_dataset.py",
            "--database",
            str(database),
            "--output",
            str(rematerialized),
        ),
        check=True,
    )

    rows = sum(
        1
        for path in rematerialized.glob("*.tfrecord.gz")
        for _ in tf.data.TFRecordDataset(str(path), compression_type="GZIP")
    )
    summary = json.loads((rematerialized / "dataset_summary.json").read_text())
    assert rows == positions == summary["examples"]

    # Recompute a component with the source archive gone. Its dependents must
    # be explicitly rebuilt; stale examples are never silently exported.
    subprocess.run(
        command(
            "build_dataset.py",
            "--output",
            str(corpus),
            "--stage",
            "participation",
            "--experiment",
        ),
        check=True,
    )
    with cache.connect(database) as connection:
        cache.require(connection, ("labels", "yaku", "analysis", "scoring"))
        with pytest.raises(ValueError, match="selection"):
            cache.require(connection, ("selection",))
    failed = subprocess.run(
        command(
            "export_dataset.py",
            "--database",
            str(database),
            "--output",
            str(rematerialized),
        ),
        capture_output=True,
        text=True,
    )
    assert failed.returncode and "selection" in failed.stderr
    subprocess.run(
        command(
            "build_dataset.py",
            "--output",
            str(corpus),
            "--stage",
            "selection",
            "--experiment",
        ),
        check=True,
    )
    assert not (corpus / "dataset_summary.json").exists()
    subprocess.run(
        command(
            "export_dataset.py",
            "--database",
            str(database),
            "--output",
            str(rematerialized),
        ),
        check=True,
    )
    assert [
        tf.train.Example.FromString(bytes(row.numpy()))
        for row in tf.data.TFRecordDataset(
            str(rematerialized / "train-00000.tfrecord.gz"),
            compression_type="GZIP",
        )
    ] == expected


def test_rebuild_rejects_an_archive_without_rank_enrichment(tmp_path):
    archives = tmp_path / "archives"
    archives.mkdir()
    archive = write_enriched_archive(archives)
    with zipfile.ZipFile(archive) as source:
        member = source.namelist()[0]
        events = [json.loads(line) for line in source.read(member).splitlines()]
    del events[0]["player_ranks"]
    with zipfile.ZipFile(archive, "w", zipfile.ZIP_DEFLATED) as output:
        output.writestr(
            member, "".join(json.dumps(event) + "\n" for event in events)
        )
    checksum = hashlib.file_digest(archive.open("rb"), "sha256").hexdigest()
    (archives / "player_ranks.json").write_text(
        json.dumps(
            {
                "sampling": player_ranks.SAMPLING,
                "years": {"2024": {"merged_sha256": checksum}},
            }
        )
    )

    result = subprocess.run(
        command(
            "build_dataset.py",
            "--archives",
            str(archives),
            "--output",
            str(tmp_path / "corpus"),
            "--experiment",
        ),
        text=True,
        capture_output=True,
    )

    assert result.returncode
    assert "player_ranks" in result.stderr


def test_afk_filter_removes_every_seat_from_two_tsumogiri_hands():
    first = all_tsumogiri_round(1)
    second = all_tsumogiri_round(2)

    retained = afk.retained_hands(
        [{"type": "start_game"}, *first, *second, {"type": "end_game"}]
    )

    assert retained == []
